// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Neon: conexión DIRECTA (non-pooling) para migraciones/introspección (necesaria para el
    // shadow DB). El runtime del cliente usa la pooled (POSTGRES_PRISMA_URL), inyectada en
    // src/lib/prisma-meta.ts. En Vercel estas env vars vienen de la integración Neon.
    url: process.env["POSTGRES_URL_NON_POOLING"],
  },
});
